baseURL = "/"
disqusShortname = ""
languageCode = "en-uk"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Wellington Frothers FC"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
name = "Schedule"
url = "https://www.sportzone.org.nz/competitions/75/wellington-sunday-football-league/wellington-sunday-football-league/winter-2020/schedule"
weight = 2
[[menu.main]]
name = "Squad"
url = "/squad-members"
weight = 1
[[menu.main]]
name = "Schedule"
url = "https://www.sportzone.org.nz/competitions/75/wellington-sunday-football-league/wellington-sunday-football-league/winter-2020/schedule"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
page = ["HTML", "JSON"]
section = ["JSON", "HTML"]
[params]
author = "Chris Chester"
contact_form_action = "#"
copyright = "&copy; 2020 Chris Chester. All Rights Reserved"
description = ""
google_analitycs_id = "UA-178004971-1"
google_tag_manager = ""
home = "Home"
logo = "images/banner/frother_logo.svg"
logoTitle = "Frothers F.C."
[params.banner]
bgImage = "images/banner/sleeves.svg"
image = "images/banner/frother_logo.svg"
title = "Wellington Frothers FC"
[params.cta]
description = "Check the table."
enable = true
image = "images/highkick.svg"
title = "Check the sunday league table"
[params.cta.button]
enable = true
label = "Open Table"
link = "https://www.sportzone.org.nz/competitions/75/wellington-sunday-football-league/wellington-sunday-football-league/winter-2020"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/frothersfc"
