author = "Chris"
baseurl = "/"
copyright = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-yuki"
title = "Sonia Yoga Time"
[[menu.main]]
name = "About Hugo"
weight = 1
[[menu.nav]]
name = "TAGS"
url = "/tags/"
weight = 5
[[menu.nav]]
name = "ABOUT"
url = "/about"
weight = 4
[[menu.nav]]
name = "BLOG"
url = "/post"
weight = 2
[[menu.nav]]
name = "HOME"
url = "/"
weight = 1
[[menu.social]]
name = "Facebook Page"
url = "/"
weight = 1
[params]
author = "Sonia"
authorwebsite = ""
avatar = ""
description = "Something legit"
displayImg = "images/display.png"
favicon = "images/logo.png"
ga_api_key = "Your Google Analytics tracking id"
logo = "images/logo.png"
mainSections = ["post"]
snsTitle = "Social"
