baseURL = "/"
disqusShortname = ""
languageCode = "en-uk"
pagination.pagerSize = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Wellington Frothers FC"
[[menu.footer]]
URL = "mailto:wellingtonfrothers@gmail.com"
name = "Contact"
weight = 1
[[menu.main]]
name = "Stats"
url ="/stats"
weight = 2
[[menu.main]]
name = "Squad Builder"
url ="/squad-builder"
weight = 2
[[menu.main]]
identifier = "Squad"
name = "Squad"
url = "/squad-members"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
page = ["HTML", "JSON"]
section = ["JSON", "HTML"]
[params]
author = "Chris Chester"
contact_form_action = "#"
copyright = "&copy; 2024 Chris Chester. All Rights Reserved"
description = "The official website for Frothers F.C., a Wellington based football club"
googleAnalytics = "G-FQC0K3GZF5"
google_tag_manager = ""
home = "Home"
images = ["images/badge.jpg"]
logo = "images/favicons/light/favicon.png"
logoTitle = "Frothers F.C."
title = "Frothers F.C."
[params.banner]
bgImage = "images/svgs/light/sleeves.svg"
image = "images/svgs/light/frother_logo.svg"
title = "Wellington Frothers FC"
[params.cta]
description = "See this weekends WSFL fixtures."
enable = true
image = "images/svgs/light/highkick.svg"
title = "Check the Schedule"
[params.cta.button]
enable = true
label = "Open Schedule"
link = "https://www.sportzone.org.nz/competitions/179/wellington-sunday-football-league/wellington-sunday-football-league/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/frothersfc"
[taxonomies]
series = "series"
