[build.environment]
  NPM_VERSION = "8.3.0"
  NODE_VERSION = "17.3.0"
  HUGO_VERSION = "0.91.2"
  
[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"
