[build.environment]
  YARN_VERSION = "1.22.22"
  NODE_VERSION = "23.9.0"
  HUGO_VERSION = "0.145.0"
  SITE_URL = "https://www.frothersfc.com/"
  
[build]
  command = "yarn run build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn run build:preview"
