[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "18.16.0"
  HUGO_VERSION = "0.91.2"
  SITE_URL = "https://www.frothersfc.com/"
  
[build]
  command = "yarn run build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn run build:preview"
