---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: matchdata
  label: Match Data
  create: all
  match: "*.toml"
  exclude: ".toml"
  templates:
  - matchdata
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm build
version: 0.69.0
