/** Declaration file generated by dts-gen */
declare module 'react-charts' {
export const alignAuto: string;

export const alignBottom: string;

export const alignBottomLeft: string;

export const alignBottomRight: string;

export const alignLeft: string;

export const alignRight: string;

export const alignTop: string;

export const alignTopLeft: string;

export const alignTopRight: string;

export const anchorBottom: string;

export const anchorCenter: string;

export const anchorClosest: string;

export const anchorGridBottom: string;

export const anchorGridLeft: string;

export const anchorGridRight: string;

export const anchorGridTop: string;

export const anchorLeft: string;

export const anchorPointer: string;

export const anchorRight: string;

export const anchorTop: string;

export const axisTypeLinear: string;

export const axisTypeLog: string;

export const axisTypeOrdinal: string;

export const axisTypeTime: string;

export const axisTypeUtc: string;

export const focusAuto: string;

export const focusClosest: string;

export const focusElement: string;

export const groupingPrimary: string;

export const groupingSecondary: string;

export const groupingSeries: string;

export const groupingSingle: string;

export const positionBottom: string;

export const positionLeft: string;

export const positionRight: string;

export const positionTop: string;

export function Chart(_ref: any): any;

export function curveBasis(t: any): any;

export function curveBasisClosed(t: any): any;

export function curveBasisOpen(t: any): any;

export function curveBundle(t: any): any;

export function curveCardinal(t: any): any;

export function curveCardinalClosed(t: any): any;

export function curveCardinalOpen(t: any): any;

export function curveCatmullRom(t: any): any;

export function curveCatmullRomClosed(t: any): any;

export function curveCatmullRomOpen(t: any): any;

export function curveLinear(t: any): any;

export function curveLinearClosed(t: any): any;

export function curveMonotoneX(t: any): any;

export function curveMonotoneY(t: any): any;

export function curveNatural(t: any): any;

export function curveStep(t: any): any;

export function curveStepAfter(t: any): any;

export function curveStepBefore(t: any): any;

export namespace Chart {
    namespace defaultProps {
        const focus: string;

        const grouping: string;

        const showVoronoi: boolean;

        function getDatumStyle(): any;

        function getDatums(d: any): any;

        function getLabel(d: any, i: any): any;

        function getPrimary(d: any): any;

        function getPrimaryAxisID(s: any): any;

        function getR(d: any): any;

        function getSecondary(d: any): any;

        function getSecondaryAxisID(s: any): any;

        function getSeriesID(d: any, i: any): any;

        function getSeriesOrder(d: any): any;

        function getSeriesStyle(series: any): any;

        function onHover(): void;

    }

}

export namespace curveBundle {
    function beta(n: any): any;

}

export namespace curveCardinal {
    function tension(n: any): any;

}

export namespace curveCardinalClosed {
    function tension(n: any): any;

}

export namespace curveCardinalOpen {
    function tension(n: any): any;

}

export namespace curveCatmullRom {
    function alpha(n: any): any;

}

export namespace curveCatmullRomClosed {
    function alpha(n: any): any;

}

export namespace curveCatmullRomOpen {
    function alpha(n: any): any;

}

}